epochs: 200
eval: True
test: True
defaults:
  - augment: augment_ED
  - train_loader: loader_ED
  #- model: ConvModel_ED
  - model: transformer_ED
  #- model: transformer_ED_clf
  #- model: transformer_recon_clf
  #- model: transformer_encoder_sep
  #- model: transformer_ED_finetune
  - optimizer: adam_schedule
  - logger: experiment
