module: conv_model_ED
name: ConvModel
params:
  target_length: 3 #should be equal to number of features 2 for x, y

loss:
  module: losses
  name: masked_norm_loss
  #name: masked_mse_loss
  gain: 10
  alpha: null