manifest_path: ../../data/train.csv
path: ../../data/
cols: ["x", "y", "z"]
num_frames: 64
batch_size:  1000
#batch_size: 32
label_map_path: ../../data/sign_to_prediction_index_map.json
data_path: ../../data/npy_64/

#val_users: ["2044", "34503", "26734", "30680", "36257", "25571"] #36257
val_users: ["36257"] 
ret_user_id: False
